# CAMBIATE LE MAIUSCOLE M di Maria in minuscole m in maria
version: '3.8'
services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: userdb
      MARIADB_DATABASE: user_db
      MARIADB_USER: appuser
      MARIADB_PASSWORD: userdb
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      MARIADB_RANDOM_ROOT_PASSWORD: "no"
    ports:
      - "3307:3306" # CAMBIATA PORTA DELLA MACCHINA IN 3307
    volumes:
      - mariadb_data:/var/lib/mysql 
      - ./mariadb/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "-puserdb"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  popola_db:
    build: ./script
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./script:/app
    working_dir: /app
    environment:
      PYTHONUNBUFFERED: 1
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: userdb
      DB_NAME: user_db
    command: ["python", "popola_db.py"]
    restart: "no"

  ollama_service:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    entrypoint: /bin/sh -c "ollama serve & sleep 2 && ollama pull gemma3:4b && tail -f /dev/null"
    restart: unless-stopped

  backend_service:
    build: ./backend
    container_name: backend_name
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src/backend
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      mariadb:
        condition: service_healthy
      ollama_service:
        condition: service_started

  frontend_service:
    build: ./frontend
    container_name: frontend_name
    environment:
      - PYTHONPATH=/app/src
    working_dir: /app/src/frontend
    command: ["uvicorn", "frontend:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    depends_on:
      - backend_service

volumes:
  mariadb_data:
  ollama: